fun sum3(a, b, c) {
  try(, catch(clojure_lang_ExceptionInfo, e, if _getMessage(e) == "return" { [value, ex_data(e)] }))
}
fun main() {
  print(sum3(1, 2, 3))
}
main()
