Traceback (most recent call last):
  File "/workspace/mochi/tests/algorithms/x/Python/web_programming/co2_emission.py", line 74, in <module>
    main()
  File "/workspace/mochi/tests/algorithms/x/Python/web_programming/co2_emission.py", line 66, in main
    entries = fetch_from_to("2020-10-01", "2020-10-03")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/mochi/tests/algorithms/x/Python/web_programming/co2_emission.py", line 64, in fetch_from_to
    return resp.data
           ^^^^^^^^^
AttributeError: 'dict' object has no attribute 'data'