run: exit status 1
Traceback (most recent call last):
  File "/workspace/mochi/tests/transpiler/x/py/group_by.py", line 10, in <module>
    _stats_groups[person["city"]] += person.value
                                     ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'value'. Did you mean: 'values'?
